# Generated by Django 4.0.3 on 2022-04-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0007_remove_create_team_create_team_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_task',
            name='trainer_task_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskdesignation', to='trainingapp.designation'),
        ),
    ]
